"""Impersonal rewording of the translator's notes (applied at build time to note bodies only).
EXACT: substring -> replacement, longest first.  REGEX: generic patterns.  residual(): first-person words left."""
import re

EXACT = [
 # ---- sentence / clause level
 ("that I do not reproduce.", "that is not reproduced."),
 ("shows a svarita-type mark that I do not reproduce", "shows a svarita-type mark that is not reproduced"),
 ("with a mark above the last letter which I read as a nasal sign", "with a mark above the last letter which is read as a nasal sign"),
 ("— but I am not certain of it", "— but the reading is not certain"),
 ("but I mark it [?];", "but it is marked [?];"),
 ("and I give it so, though I have not verified it", "and it is given so, though it has not been verified"),
 ("are my best reading of the image", "are a best reading of the image"),
 ("technical objections and replies that I do not reproduce", "technical objections and replies that are not reproduced"),
 ("whose precise conventions I could not convert to Devanagari accent-signs with confidence", "whose precise conventions could not be converted to Devanagari accent-signs with confidence"),
 ("for every viṣṭuti I added up the three paryāyas", "for every viṣṭuti the three paryāyas were added up"),
 ("and I record the print]", "and the print is recorded]"),
 ("the print's numeral is small and I give it with [?]", "the print's numeral is small and is given with [?]"),
 ("my first reading of the printed number", "the first reading of the printed number"),
 ("and I have given \"6-73-1\" with a [?], because I could not read the printed digits and I am relying on the wording", "and \"6-73-1\" is given with a [?], because the printed digits could not be read and the wording is relied on"),
 ("on pp. 136–139 I first wrote this technical term as", "on pp. 136–139 this technical term was first written as"),
 ("Correction to my own IAST above", "Correction to the IAST above"),
 ("is a slip in my transliteration", "is a slip in the transliteration"),
 ("For the deity-distribution I follow the printed heading block below and the Kannada rendering", "For the deity-distribution the printed heading block below and the Kannada rendering are followed"),
 ("I give the runs as tallied from that page", "the runs are given as tallied from that page"),
 ("my gloss in this paragraph is outline only", "the gloss in this paragraph is outline only"),
 ("marks stretches I could not read at 150 dpi", "marks stretches that could not be read at 150 dpi"),
 ("is as I read the small print [?]", "is as read from the small print [?]"),
 ("agree with those I know", "agree with the standard numbering"),
 ("where I could compare", "where comparison was possible"),
 ("those I could compare against the standard numbering agree", "those that could be compared against the standard numbering agree"),
 ("the remaining numerals I could not read at 150 dpi", "the remaining numerals could not be read at 150 dpi"),
 ("I could not settle the exact letters and mark them [?].", "The exact letters could not be settled and are marked [?]."),
 ("I did not chase the numerals.", "The numerals were not pursued."),
 ("I do not claim to have followed every step of it.", "Not every step of it is claimed to have been followed."),
 ("I do not reconcile them.", "They are not reconciled."),
 ("I do not transcribe the argument line by line: it is", "The argument is not transcribed line by line: it is"),
 ("I do not translate Yāska's comment word for word, but its sense", "Yāska's comment is not translated word for word, but its sense"),
 ("I follow the print's direction here;", "The print's direction is followed here;"),
 ("I give *kāmam ā*, the form", "*kāmam ā* is given, the form"),
 ("I give it as I read it and mark it [?].", "It is given as read and marked [?]."),
 ("I give it as printed, and the English is mine.", "It is given as printed, and the English is editorial."),
 ("I give it as printed, with the second name uncertain", "It is given as printed, with the second name uncertain"),
 ("I give it as printed.", "It is given as printed."),
 ("I give it as read.", "It is given as read."),
 ("I give it in three layers.", "It is given in three layers."),
 ("I give it so.", "It is given so."),
 ("I give it with [?], and", "It is given with [?], and"),
 ("I give it with the word-break, since", "It is given with the word-break, since"),
 ("I give only the first, which agrees", "Only the first is given, which agrees"),
 ("I give only the words treated and the sūtras I could read; numerals marked [?] are uncertain.", "Only the words treated and the sūtras that could be read are given; numerals marked [?] are uncertain."),
 ("I give only the words treated and the sūtras I could read.", "Only the words treated and the sūtras that could be read are given."),
 ("I give only the portions I could read.", "Only the portions that could be read are given."),
 ("I give only the portions I read.", "Only the portions that were read are given."),
 ("I give only the", "Only the"),    # fallback for "I give only the first/…" handled above; keeps grammar loose but impersonal
 ("I give the IAST and the Devanagari heading of the pair, as", "The IAST and the Devanagari heading of the pair are given, as"),
 ("I give the Sanskrit as read and a translation in outline, saying where the sense is uncertain.", "The Sanskrit is given as read, with a translation in outline, saying where the sense is uncertain."),
 ("I give the Saṃhitā in sandhi, *ya īṅkhayanti*, as", "The Saṃhitā is given in sandhi, *ya īṅkhayanti*, as"),
 ("I give the corrected word.", "The corrected word is given."),
 ("I give the divisions as I read the printed signs.", "The divisions are given as read from the printed signs."),
 ("I give the figures that continue the run of Sūkta 14 and mark them unreliable", "The figures that continue the run of Sūkta 14 are given and marked unreliable"),
 ("I give the legible portions.", "The legible portions are given."),
 ("I give the legible portion.", "The legible portion is given."),
 ("I give the sense and not a reading of the garbled stretch.", "The sense is given, not a reading of the garbled stretch."),
 ("I give the sense of the verse only in outline, because its last words are not clear to me.", "The sense of the verse is given only in outline, because its last words are not clear."),
 ("I give the sequences whose sums are 17 and which agree with the digit strings I could read.", "The sequences given are those whose sums are 17 and which agree with the digit strings that could be read."),
 ("I give the standard form of this well-known verse and flag the discrepancy.", "The standard form of this well-known verse is given and the discrepancy flagged."),
 ("I give the strings exactly as read and do not adjust them.", "The strings are given exactly as read and are not adjusted."),
 ("I give the words as far as I could read them and do not complete them.", "The words are given as far as they could be read and are not completed."),
 ("I give the words as intended.", "The words are given as intended."),
 ("I give the words undivided, as I cannot make out the dividing signs.", "The words are given undivided, as the dividing signs cannot be made out."),
 ("I give the words undivided.", "The words are given undivided."),
 ("I give them as read and without translating.", "They are given as read and without translating."),
 ("I give them as the Sanskrit above and the Kannada count require, and flag the line [?]", "They are given as the Sanskrit above and the Kannada count require, and the line is flagged [?]"),
 ("I give them only where reasonably legible, with [?] where not.", "They are given only where reasonably legible, with [?] where not."),
 ("I give them with a query.", "They are given with a query."),
 ("I had first written \"Pā. 6-1-223\" from memory, and that attribution has been withdrawn above;", "\"Pā. 6-1-223\" had first been written from memory, and that attribution has been withdrawn above;"),
 ("I have given its outline only,", "Its outline only is given,"),
 ("I have joined them.", "They have been joined."),
 ("I have marked [?] where I could not confirm them.", "[?] marks where they could not be confirmed."),
 ("I have not checked the rest.", "The rest has not been checked."),
 ("I have not corrected it from outside knowledge, and a few of its spellings look irregular, which I leave as printed.", "It has not been corrected from outside knowledge, and a few of its spellings look irregular; they are left as printed."),
 ("I leave it flagged and unrestored.", "It is left flagged and unrestored."),
 ("I leave it unexplained [?].", "It is left unexplained [?]."),
 ("I mark [?] where a word is not clearly read.", "[?] marks where a word is not clearly read."),
 ("I note that the same Ṛk was already quoted in Sūkta 3, p. 25 of this file's earlier text.", "The same Ṛk was already quoted in Sūkta 3, p. 25 of this volume's earlier text."),
 ("I note this rather than supply one.", "This is noted rather than a number supplied."),
 ("I note where the numbers differ from the Sanskrit page.", "Where the numbers differ from the Sanskrit page this is noted."),
 ("I read \"tuj\" as the root.", "\"tuj\" is read as the root."),
 ("I read it as continuing the sentence, and note the sense is a little loose.", "It is read as continuing the sentence, and the sense is a little loose."),
 ("I read it as given and note that the Bhāṣya's gloss", "It is read as given; the Bhāṣya's gloss"),
 ("I read the word as \"vāghata.\"", "The word is read as \"vāghata.\""),
 ("I read them as \"4\" and \"8,\"", "They are read as \"4\" and \"8,\""),
 ("I read them at 150 dpi, not enlarged.", "They were read at 150 dpi, not enlarged."),
 ("I record both as printed and do not choose.", "Both are recorded as printed, without choosing."),
 ("I record both spellings as printed.", "Both spellings are recorded as printed."),
 ("I record it as printed.", "It is recorded as printed."),
 ("I record only its drift.", "Only its drift is recorded."),
 ("I record this rather than present the number as read.", "This is recorded rather than the number being presented as read."),
 ("I take it so, but flag it [?].", "It is taken so, but flagged [?]."),
 ("I take it to be \"ṛtvik-nāmasu,\"", "It is taken to be \"ṛtvik-nāmasu,\""),
 ("I transcribe it letter by letter and mark doubtful words.", "It is transcribed letter by letter, with doubtful words marked."),
 ("I transcribe the print as it stands.", "The print is transcribed as it stands."),
 ("I transcribe them as I read them, with [?], and give their sense in outline rather than a line-by-line translation.", "They are transcribed as read, with [?], and their sense is given in outline rather than as a line-by-line translation."),
 ("I translate no name that the source does not itself explain.", "No name is translated that the source does not itself explain."),
 ("I translate only what the source's own explanation supports.", "Only what the source's own explanation supports is translated."),
 ("one word is unclear to me and flagged", "one word is unclear and flagged"),
 ("with a letter-group that I read as", "with a letter-group read as"),
 ("which I had read as \"tenth,\"", "which had been read as \"tenth,\""),
 ("that I read on pp. 175–201", "read on pp. 175–201"),
 ("I leave the earlier notes as written and flag them", "The earlier notes are left as written and flagged"),
 ("as far as I can follow,", "as far as it can be followed,"),
 ("as I read the print,", "as read in the print,"),
 ("a form I read as", "a form read as"),
 ("where I had expected the *eighth* given the page headers I read as", "where the *eighth* had been expected given the page headers read as"),
 ("as I could make it out", "as it could be made out"),
 ("and I record the discrepancy without resolving it", "and the discrepancy is recorded without being resolved"),
 ("are given as I read them", "are given as read"),
 ("and I give no translation of them", "and no translation of them is given"),
 ("or in my reading of a small numeral", "or in the reading of a small numeral"),
 ("as best I could read them", "as best they could be read"),
 ("and I give only the portions I read", "and only the portions that were read are given"),
 ("I could not read the numerals reliably", "the numerals could not be read reliably"),
 ("was clipped in my enlargement", "was clipped in the enlargement"),
 ("the sūtras I could read with confidence are kept", "the sūtras that could be read with confidence are kept"),
 ("which I read at ordinary enlargement only", "which was read at ordinary enlargement only"),
 ("where I could not be sure of a digit", "where a digit was not certain"),
 ("every reference I am not sure of is marked [?]", "every reference that is not certain is marked [?]"),
 ("where I am not sure of a digit", "where a digit is not certain"),
 ("I could not read reliably", "could not be read reliably"),
 ("read as best I can and all marked [?]", "read as well as possible and all marked [?]"),
 ("read as best I can;", "read as well as possible;"),
 ("was written before I had read to the foot of p. 169's grammar", "was written before the foot of p. 169's grammar had been read"),
 ("where two read differently I have written the alternatives", "where two read differently the alternatives are written"),
 ("sūtras I could read with confidence are kept", "sūtras that could be read with confidence are kept"),
 ("at first I read the opening of this sūtra as", "at first the opening of this sūtra was read as"),
 ("that I read as the avagraha-division", "that is read as the avagraha-division"),
 ("but cannot make out with certainty, so I give the word undivided", "but cannot be made out with certainty, so the word is given undivided"),
 ("the clause I give as", "the clause given as"),
 ("so I mark it [?] and do not rely on it", "so it is marked [?] and not relied on"),
 ("In the Saṃhitā the print runs \"sanedimaṃ\" (for \"sanet imaṃ\") together, as I give it.", "In the Saṃhitā the print runs \"sanedimaṃ\" (for \"sanet imaṃ\") together, as given."),
 ("as I read it.", "as read."),
 ("as I read the printed sign", "as read from the printed sign"),
 ("so I give no number", "so no number is given"),
 ("and I give it flagged", "and it is given flagged"),
 ("with marks I read as", "with marks read as"),
 ("and I give it so;", "and it is given so;"),
 ("looks to me to be a printer's slip", "looks like a printer's slip"),
 ("and I transcribe it as I make it out", "and it is transcribed as it can be made out"),
 ("is my best reading", "is the best reading"),
 ("on p. 43 I gave it as", "on p. 43 it was given as"),
 ("and I give only its tail", "and only its tail is given"),
 ("are crowded in the print and I do not reproduce them", "are crowded in the print and are not reproduced"),
 ("and I do not give them", "and are not given"),
 ("the \"seventh varga\" notes I recorded at", "the \"seventh varga\" notes recorded at"),
 ("that I read as *ṛta…* [?] and cannot complete", "that is read as *ṛta…* [?] and cannot be completed"),
 ("The English is my rendering;", "The English is an editorial rendering;"),
 ("The English is mine.", "The English is editorial."),
 ("a Kannada digit pair I could not read with certainty", "a Kannada digit pair that could not be read with certainty"),
 ("because I could not read them with certainty", "because they could not be read with certainty"),
 ("are crowded and I do not reproduce them", "are crowded and are not reproduced"),
 ("which is what I follow", "which is what is followed"),
 ("is my best reading; \"kubra,\"", "is a best reading; \"kubra,\""),
 ("not certain to me", "not certain"),
 ("is my reconstruction of the glosses", "is a reconstruction of the glosses"),
 ("which I read as \"bhavema eva.\"", "which is read as \"bhavema eva.\""),
 ("is printed as I give it;", "is printed as given;"),
 ("as I read them, run", "as read, run"),
 ("slightly unclear to me, and I give it as printed", "slightly unclear, and it is given as printed"),
 ("— I give it with a query.", "— it is given with a query."),
 ("not clear to me beyond the first and the third — I give them as read", "not clear beyond the first and the third — they are given as read"),
 ("I could not read it reliably, so I omit its numbers rather than guess", "it could not be read reliably, so its numbers are omitted rather than guessed"),
 ("and I give it only in the form I could read", "and it is given only in the form that could be read"),
 ("are as I read the Kannada print", "are as read from the Kannada print"),
 ("and I mark them all [?]", "and all are marked [?]"),
 ("and I do not give them.", "and are not given."),
 ("The ones I confirmed against my memory of the standard Aṣṭādhyāyī numbering", "Those that agree with the standard Aṣṭādhyāyī numbering as recalled"),
 ("I give without comment", "are given without comment"),
 ("and I record it as read", "and it is recorded as read"),
 ("The page is crowded and I do not reproduce its more technical sub-arguments.", "The page is crowded and its more technical sub-arguments are not reproduced."),
 ("— I read these as the varga-end marks;", "— these are read as the varga-end marks;"),
 ("has the counts as I give them;", "has the counts as given;"),
 ("is printed as I give it and I flag it as hard to read", "is printed as given and is flagged as hard to read"),
 ("and I record the print as it stands", "and the print is recorded as it stands"),
 ("and my rendering of its last clause", "and the rendering of its last clause"),
 ("and I may have been guided by", "and the reading may have been guided by"),
 ("as best I could read it", "as best it could be read"),
 ("which I flag rather than alter", "which is flagged rather than altered"),
 ("as I have read it", "as read"),
 ("are as I read the small numerals", "are as read from the small numerals"),
 ("and I say so again at that point", "and this is stated again at that point"),
 ("are mine, based on", "are editorial, based on"),
 ("and I do not add one", "and none is added"),
 ("and I give the order its example list shows", "and the order its example list shows is given"),
 ("below my confidence threshold", "below the confidence threshold"),
 ("which I give as read", "which are given as read"),
 ("with glosses of my own, tentative, where I can give them", "with glosses, editorial and tentative, where they can be given"),
 ("I could not read them reliably", "they could not be read reliably"),
 ("the left edge of my enlargement, and I mark it [?]", "the left edge of the enlargement, and is marked [?]"),
 ("The Ṛk-numbering of the deities I take from", "The Ṛk-numbering of the deities is taken from"),
 ("and per the standing convention I characterize the argument in outline", "and per the standing convention the argument is characterized in outline"),
 ("every sūtra I could read with confidence is kept", "every sūtra that could be read with confidence is kept"),
 ("unreliable in my reading", "unreliable in the reading"),
 ("where I could not read or condense them", "where they could not be read or condensed"),
 ("in my reading of the small numerals, and I record it without resolving it", "in the reading of the small numerals, and is recorded without being resolved"),
 ("a numeral I cannot read", "a numeral that cannot be read"),
 ("for me to reproduce line by line; the outline above is my best summary", "to be reproduced line by line; the outline above is a best summary"),
 ("I give each paryāya as runs", "each paryāya is given as runs"),
 ("the counts are my own tallies", "the counts are tallies"),
 ("Where a name is uncertain in the print I mark it [?];", "Where a name is uncertain in the print it is marked [?];"),
 ("Words I could not read are marked [?]", "Words that could not be read are marked [?]"),
 ("against my own knowledge of the Aṣṭādhyāyī", "against the standard Aṣṭādhyāyī"),
 ("cut off in my enlargement", "cut off in the enlargement"),
 ("[?] marks letters I could not read with confidence", "[?] marks letters that could not be read with confidence"),
 ("[?] marks my uncertainty.", "[?] marks uncertainty."),
 ("[?] where I am unsure of a digit.", "[?] where a digit is uncertain."),
 ("and I do not give a reading of the unclear stretch", "and no reading of the unclear stretch is given"),
 ("and I give only what I read clearly", "and only what was read clearly is given"),
 ("where I am not sure", "where uncertain"),
 ("my paraphrase;", "paraphrase;"),
 ("my rendering of the Kannada exposition, tentative", "rendering of the Kannada exposition, tentative"),
 ("my rendering; the Sanskrit", "editorial rendering; the Sanskrit"),
 ("I have kept the printed words as far as legible", "the printed words have been kept as far as legible"),
 ("my translation of the Kannada exposition", "translation of the Kannada exposition"),
 ("number illegible to me", "number illegible"),
 ("cut off in my slice", "cut off in the slice"),
 ("transcribed as I read it", "transcribed as read"),
 ("the number is not legible to me", "the number is not legible"),
 ("this is my reading of a four-line", "this is a reading of a four-line"),
 ("and I could not read them with confidence", "and could not be read with confidence"),
 ("whose nasal sign I flagged at p. 111", "whose nasal sign was flagged at p. 111"),
 ("Mine; the verses are the standard homage verses of this series.", "The translation is editorial; the verses are the standard homage verses of this series."),
]
EXACT.sort(key=lambda p: -len(p[0]))

EXACT += [
 (", which I follow in the translation", ", which is followed in the translation"),
 ("and I leave it as read, [?]", "and is left as read, [?]"),
 ("so I translate so", "so it is translated so"),
 ("remark — I read from the print, which is crowded", "remark — read from the print, which is crowded"),
 ("the final verb I read as an imperative from", "the final verb is read as an imperative from"),
 ("? I do not complete it;", "? It is not completed;"),
 ("— I read \"syāvarakam\" as", "— \"syāvarakam\" is read as"),
 ("is my reading of", "is the reading of"),
 ("which I cannot make into sense", "which cannot be made into sense"),
 ("and I normalise to", "and is normalised to"),
 ("— I could not settle the middle.", "— the middle could not be settled."),
 ("and my reading of the first ṛk's first word", "and the reading of the first ṛk's first word"),
 ("not my *samyag añcanaṃ* [?]", "not *samyag añcanaṃ*, the earlier reading [?]"),
 ("Gloss mine, tentative, as the first line is uncertain in my reading.", "Gloss editorial and tentative, as the first line is uncertain."),
 ("I checked this line on a 300-dpi slice.", "This line was checked on a 300-dpi slice."),
 ("I could not read the \"iti nighāta-pratiṣedhaḥ\" citation beyond these opening words.", "The \"iti nighāta-pratiṣedhaḥ\" citation could not be read beyond these opening words."),
 ("I do not alter either, and note it as doubtful, [?].", "Neither is altered, and it is noted as doubtful, [?]."),
 ("I do not read it as *ṣu* and do not decide it;", "It is not read as *ṣu* and is not decided;"),
 ("I do not understand the remark [?].", "The remark is not understood [?]."),
 ("I follow each as printed.", "Each is followed as printed."),
 ("I follow the Pada.", "The Pada is followed."),
 ("I follow the print.", "The print is followed."),
 ("I give \"1, [2?], 4, 6\", doubtful [?].", "\"1, [2?], 4, 6\" is given, doubtful [?]."),
 ("I give \"1–2 … 3–14\", doubtful [?].", "\"1–2 … 3–14\" is given, doubtful [?]."),
 ("I give \"somāśvendriya…\" [?].", "\"somāśvendriya…\" is given [?]."),
 ("I give \"āśvāvat\" in the tail as printed", "\"āśvāvat\" is given in the tail as printed"),
 ("I give *aṣṭāśri* as in the bhāṣya.", "*aṣṭāśri* is given as in the bhāṣya."),
 ("I give *ohaṃ* as the Pada does.", "*ohaṃ* is given as the Pada does."),
 ("I give *vahnayaḥ*.", "*vahnayaḥ* is given."),
 ("I give both as printed.", "Both are given as printed."),
 ("I give each in three layers, with the Ṛgveda references as read — all numerals [?] — and a mine-and-tentative gloss", "Each is given in three layers, with the Ṛgveda references as read — all numerals [?] — and an editorial and tentative gloss"),
 ("I give it as printed [?].", "It is given as printed [?]."),
 ("I give it as printed, and read it as", "It is given as printed, and read as"),
 ("I give it as read, [?].", "It is given as read, [?]."),
 ("I give it as read, with [?] where a word is doubtful.", "It is given as read, with [?] where a word is doubtful."),
 ("I give it as the Kannada states,", "It is given as the Kannada states,"),
 ("I give it as the Pada does.", "It is given as the Pada does."),
 ("I give no Devanagari for it, to avoid completing garbled text;", "No Devanagari is given for it, to avoid completing garbled text;"),
 ("I give the Devanagari as printed, doubtful:", "The Devanagari is given as printed, doubtful:"),
 ("I give the Pada as printed with [?], not adjusting it.", "The Pada is given as printed with [?], not adjusted."),
 ("I give the Pada as printed.", "The Pada is given as printed."),
 ("I give the Saṃhitā \"tṛṣu cyavāno\" as printed, doubtful:", "The Saṃhitā \"tṛṣu cyavāno\" is given as printed, doubtful:"),
 ("I give the Saṃhitā as printed and mark the word-division as the Saṃhitā's only:", "The Saṃhitā is given as printed, with the word-division marked as the Saṃhitā's only:"),
 ("I give the bhāṣya under its proper heading.", "The bhāṣya is given under its proper heading."),
 ("I give the gloss as printed [sic?].", "The gloss is given as printed [sic?]."),
 ("I give the mantra, as printed, in three layers:", "The mantra is given, as printed, in three layers:"),
 ("I give the sense from the Pratipadārtha.", "The sense is given from the Pratipadārtha."),
 ("I give the words as best read.", "The words are given as best read."),
 ("I give them as read and mark every one [?];", "They are given as read, every one marked [?];"),
 ("I give them as read, [?];", "They are given as read, [?];"),
 ("I have not attempted to reconcile the two lists.", "No attempt has been made to reconcile the two lists."),
 ("I have not resolved it, see note below", "It has not been resolved, see note below"),
 ("I have not tried to reconcile them against outside lists", "No attempt has been made to reconcile them against outside lists"),
 ("I read \"*sthāpayāṃ cakṛṣe*\" doubtfully, [?];", "\"*sthāpayāṃ cakṛṣe*\" is read doubtfully, [?];"),
 ("I read \"*svargaṃ*\" for", "\"*svargaṃ*\" is read for"),
 ("I read \"*tān* [?]\" and connect it, as the print does,", "\"*tān* [?]\" is read and connected, as in the print,"),
 ("I read \"*yasmān nibarhayaḥ*\", [?].", "\"*yasmān nibarhayaḥ*\" is read, [?]."),
 ("I read *atáseṣu* with the Pada and the Pratipadārtha.", "*atáseṣu* is read with the Pada and the Pratipadārtha."),
 ("I read *avan* + *sv…* as the Pada's", "*avan* + *sv…* is read as the Pada's"),
 ("I read *chvitryaṃ*, i.e.", "*chvitryaṃ* is read, i.e."),
 ("I read *etad uktaṃ bhavati*, [?].", "*etad uktaṃ bhavati* is read, [?]."),
 ("I read *havirdātre*, [?].", "*havirdātre* is read, [?]."),
 ("I read *kāmam eṣām* from the Pada.", "*kāmam eṣām* is read from the Pada."),
 ("I read *tuviṣmān* per the Pada.", "*tuviṣmān* is read per the Pada."),
 ("I read *yad annam* [?].", "*yad annam* is read [?]."),
 ("I read from the Pratipadārtha \"overcoming enemies\".", "\"Overcoming enemies\" is read from the Pratipadārtha."),
 ("I read it as *prayaḥ*, [?].", "It is read as *prayaḥ*, [?]."),
 ("I read it as *sam indra rāyā*:", "It is read as *sam indra rāyā*:"),
 ("I read it as a printer's mark and do not reproduce it.", "It is read as a printer's mark and is not reproduced."),
 ("I read it as the Rik number 5 [?].", "It is read as the Rik number 5 [?]."),
 ("I read it so because", "It is read so because"),
 ("I read it with the anuvāda below,", "It is read with the anuvāda below,"),
 ("I read the Saṃhitā's *tiraścēṣyan* as *tiraśceṣyan*", "The Saṃhitā's *tiraścēṣyan* is read as *tiraśceṣyan*"),
 ("I read the first word as printed", "The first word is read as printed"),
 ("I read the line-end as *ucchad apa sridhaḥ*, from the Pada, [?].", "The line-end is read as *ucchad apa sridhaḥ*, from the Pada, [?]."),
 ("I read the print's \"नोत\" as", "The print's \"नोत\" is read as"),
 ("I read the sentence as above, with the damaged letters as", "The sentence is read as above, with the damaged letters as"),
 ("I reproduce it as printed, [sic].", "It is reproduced as printed, [sic]."),
 ("I separate it for reading.", "It is separated for reading."),
 ("I take it as the Rik number 5, unexplained [?].", "It is taken as the Rik number 5, unexplained [?]."),
 ("I take the sense \"he gives these", "The sense taken is \"he gives these"),
 ("I take the sense from the Pratipadārtha,", "The sense is taken from the Pratipadārtha,"),
 ("is mine-normalised from", "is normalised from"),
 ("My glosses, mine and tentative:", "Glosses, editorial and tentative:"),
 ("and I take the Pada's *tṛṣu | aviṣyan*", "and the Pada's *tṛṣu | aviṣyan* is taken"),
 ("which I could not resolve — probably", "which could not be resolved — probably"),
 ("and I leave it as [?]", "and it is left as [?]"),
 ("— I give it as printed, [?]", "— it is given as printed, [?]"),
 ("— I read \"*bṛhato mahato*\", which", "— \"*bṛhato mahato*\" is read, which"),
 ("the punctuation of *abhiṣṭayaḥ … ūtayaḥ* is mine", "the punctuation of *abhiṣṭayaḥ … ūtayaḥ* is editorial"),
 ("I cannot resolve — the line is crowded — and leave it [?]", "cannot be resolved — the line is crowded — and is left [?]"),
 ("which I gave as", "which was given as"),
 ("which I divide with the Pada", "which is divided with the Pada"),
 ("as I had read.", "as had been read."),
 ("which I cannot settle at 150 dpi and mark [?]", "which cannot be settled at 150 dpi and is marked [?]"),
 ("and, as I see it, runs over the page", "and, as it appears, runs over the page"),
 ("where I read *uṣodevate*", "where *uṣodevate* is read"),
 ("and I rely on it for the rule", "and it is relied on for the rule"),
 ("which I at first left unfinished with a placeholder", "which was at first left unfinished with a placeholder"),
 ("The middle of this passage I cannot make out", "The middle of this passage cannot be made out"),
 ("The others I leave unglossed.", "The others are left unglossed."),
 ("where I read \"div-\" with \"iṣṭa\"", "where \"div-\" with \"iṣṭa\" is read"),
 ("in my transcription for pra-matim", "in the transcription for pra-matim"),
 ("is my reading of \"rephādeśaḥ\" [?]", "is the reading of \"rephādeśaḥ\" [?]"),
 ("— I take it as the verb *ayoyavīt* of the Pada;", "— it is taken as the verb *ayoyavīt* of the Pada;"),
 ("for the word I give as *prasnuta°*", "for the word given as *prasnuta°*"),
 ("with a cluster that I read as *āran*, [?]", "with a cluster read as *āran*, [?]"),
 ("— I read it as the Pada's *adadāḥ*", "— it is read as the Pada's *adadāḥ*"),
 ("— I take the Pada's *yā mānuṣeṣu | asi | tasya | rājā*, pending", "— the Pada's *yā mānuṣeṣu | asi | tasya | rājā* is taken, pending"),
 ("so I treat the quotation as", "so the quotation is treated as"),
 ("my glosses, mine and tentative:", "glosses, editorial and tentative:"),
 ("was my slip.", "was a slip."),
 ("my earlier note read them as", "the earlier note read them as"),
 ("The word I give as \"ciketanti\"", "The word given as \"ciketanti\""),
 ("were my own premature remark", "were a premature remark"),
 ("of my earlier flag", "of the earlier flag"),
 ("Translation mine from the Sanskrit", "Translation editorial, from the Sanskrit"),
 ("Translation mine;", "Translation editorial;"),
 ("Translation of the ṛk mine, tentative;", "Translation of the ṛk editorial and tentative;"),
 ("as far as I know it [?]", "as far as is known [?]"),
 ("that I read as *śṛṅgiṇam*", "that is read as *śṛṅgiṇam*"),
 ("is not legible to me [?]", "is not legible [?]"),
 ("my own provisional rendering", "provisional rendering"),
 ("and I give them as read, [?]", "and are given as read, [?]"),
 ("and I did not chase the small numerals", "and the small numerals were not pursued"),
 ("and I did not chase the numerals", "and the numerals were not pursued"),
 ("and I have not reproduced every step", "and not every step is reproduced"),
 ("and I have not reproduced its argument", "and its argument is not reproduced"),
 ("where the print is crowded I mark [?]", "where the print is crowded [?] is marked"),
 ("the numerals are small and I give them with [?]; my glosses are mine and tentative", "the numerals are small and are given with [?]; glosses are editorial and tentative"),
 ("my glosses are mine and tentative", "glosses are editorial and tentative"),
 ("my sense, mine and tentative:", "the sense, editorial and tentative:"),
]
EXACT.sort(key=lambda p: -len(p[0]))

_REGEX_OLD = [
 (re.compile(r"\bmine and tentative\b"), "editorial and tentative"),
 (re.compile(r"\bmine, tentative\b"), "editorial and tentative"),
 (re.compile(r"\b([Gg]losses|[Gg]loss)( (?:are|is))? mine\b"), r"\1\2 editorial"),
 (re.compile(r"\b(English glosses|glosses below|glosses of the pairs[^.]*?)( are)? mine\b"), r"\1\2 editorial"),
 (re.compile(r"\bare mine\b"), "are editorial"),
 (re.compile(r"\bmy glosses\b"), "glosses"),
 (re.compile(r"\bmy sense\b"), "the sense"),
 (re.compile(r"\band I give them with \[\?\]"), "and are given with [?]"),
 (re.compile(r"\bmy gloss\b"), "the gloss"),
 (re.compile(r"\bas I read (it|them)\b"), "as read"),
 (re.compile(r"\bI give only its drift\b"), "only its drift is given"),
 (re.compile(r"\bin my enlargement\b"), "in the enlargement"),
]


def _ppart(w):
    return {'transcribe':'transcribed','follow':'followed','complete':'completed','reproduce':'reproduced','read':'read','translate':'translated','give':'given','alter':'altered','decide':'decided','resolve':'resolved','supply':'supplied'}.get(w, w+'ed')

EXACT += [
 ("for what I read as", "for what is read as"),
 ("which I read as:", "which is read as:"),
 ("in the print as I see it", "in the print as it appears"),
 ("I give it only in the standard form and the number as read", "it is given only in the standard form and the number as read"),
 ("without a number I could read", "without a number that could be read"),
 ("I give the name as printed", "the name is given as printed"),
 ("I give no firm sense", "no firm sense is given"),
 ("whose numeral I read as", "whose numeral is read as"),
 ("I give no firmer reading", "no firmer reading is given"),
 ("I give its substance, not word by word", "its substance is given, not word by word"),
 ("I transcribe it as printed, with *three layers*, and do not complete any syllable I could not read", "it is transcribed as printed, with *three layers*, and no syllable that could not be read is completed"),
 ("I read the sense from the Kannada", "the sense is read from the Kannada"),
 ("and I do not complete them, [?]", "and they are not completed, [?]"),
 ("the print is crowded, I give it as read, doubtful", "the print is crowded, it is given as read, doubtful"),
 ("I note it as read, [?]", "it is noted as read, [?]"),
 ("I read it as *ñnityādir nityam*, [?]", "it is read as *ñnityādir nityam*, [?]"),
]
EXACT.sort(key=lambda p: -len(p[0]))

REGEX = [
 (re.compile(r",? my (?:own )?gloss(?:es)?,? \*(?:mine|editorial) and tentative\*"), ", with an editorial and tentative gloss"),
 (re.compile(r"\bwith my own gloss,? \*editorial and tentative\*"), "with an editorial and tentative gloss"),
 (re.compile(r"\bI give each in three layers\b"), "each is given in three layers"),
 (re.compile(r"\(mine, very tentative"), "(editorial, very tentative"),
 (re.compile(r"\bmine, very tentative"), "editorial, very tentative"),
 (re.compile(r"\bas I read the (?=\w)"), "as read from the "),
 (re.compile(r"\bas I know it\b"), "as known"),
 (re.compile(r"\bI recall this as\b"), "recalled as"),
 (re.compile(r"\] I give with \[\?\]"), "] is given with [?]"),
 (re.compile(r"\bmy reading of\b"), "the reading of"),
 (re.compile(r"\bwhose numbers I could read\b"), "whose numbers could be read"),
 (re.compile(r"\bI did not chase them\b"), "they were not pursued"),
 (re.compile(r"\b(unclear|uncertain|clear|legible|certain) to me\b"), r"\1"),
 (re.compile(r"\bwhich I cannot read\b"), "which cannot be read"),
 (re.compile(r"\ba way I could not read\b"), "a way that could not be read"),
 (re.compile(r"\band I do not (transcribe|follow|complete|reproduce|read|translate) it\b"), lambda m: "and it is not " + _ppart(m.group(1))),
 (re.compile(r"\bI find \*\*no"), "there is **no"),
 (re.compile(r"\bI have not trusted them\b"), "they have not been trusted"),
 (re.compile(r"\bI give a number only where I could read it\b"), "a number is given only where it could be read"),
 (re.compile(r"\ba rule is given a number only where I read it\b"), "a rule is given a number only where it was read"),
 (re.compile(r"\bI have marked \[\?\] and not reconciled\b"), "marked [?] and not reconciled"),
 *_REGEX_OLD,
]

def fix(text):
    for old, new in EXACT:
        if old in text: text = text.replace(old, new)
    for rx, rep in REGEX:
        text = rx.sub(rep, text)
    return text

AUTHOR_VOICE = re.compile(r"\b(I|I'm|I've|I'd|my|myself)\b|\bmine\b(?!\s*['’)])|\bto me\b|\bme to\b")
def residual(text):
    text = re.sub(r'"[^"]*"|“[^”]*”', '""', text)
    """First-person author-voice words still present, ignoring those inside Sanskrit-gloss quotes like ('this is mine')."""
    out = []
    for m in AUTHOR_VOICE.finditer(text):
        ctx = text[max(0, m.start() - 40): m.end() + 40]
        if "this is mine" in ctx: continue
        out.append(ctx.replace('\n', ' '))
    return out
